config/routes.rb
Ndsc::Application.routes.draw do
  get "speakers/index"

  ActiveAdmin.routes(self)
  root to: 'thirteen#index'
  devise_for :users, controllers: {registrations: 'registrations'}
  resources :users, only: [:index, :show]
  resources :speakers, only: [:index]
  get '/program' => 'thirteen#program', as: "program"
  get '/housing' => 'thirteen#housing', as: "housing"
  get '/transportation' => 'thirteen#transportation', as: "transportation"
  get '/contact' => 'thirteen#contact', as: "contact"

  get '/about' => 'pages#about', as: "about"
  get '/host' => 'pages#host', as: "host"
  get '/gallery' => 'pages#gallery', as: "gallery"
end

app/models/event.rb
class Event < ActiveRecord::Base
	has_many :event_speakers
	has_many :speakers, through: :event_speakers
  attr_accessible :description, :end_time, :name, :session, :show_in_program, :start_time, :venue,
  								:workshop
  def agenda_time
    "#{start_time.strftime('%l:%M')} - #{end_time.strftime('%l:%M%P')}"
  end
end

app/models/event_speaker.rb
class EventSpeaker < ActiveRecord::Base
  belongs_to :event
  belongs_to :speaker
  attr_accessible :event_id, :speaker_id, :priority
end

app/models/speaker.rb
class Speaker < ActiveRecord::Base
	has_many :event_speakers
	has_many :events, through: :event_speakers
  attr_accessible :description, :email, :first_name, :image, :keynote, :last_name, :notes,
  								:organization, :phone_number, :suffix, :title
  validates :first_name, presence: true
  mount_uploader :image, ImageUploader

  def name
  	"#{first_name} #{last_name}"
  end
  def professional_name
  	"#{title} #{first_name} #{last_name}#{', ' + suffix if suffix}"
  end
  def priority
    EventSpeaker.find_by_speaker_id(id).priority
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are: :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :description, :email, :name, :password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
	# before_filter :authenticate_user!

  def authenticate_admin!
    redirect_to new_user_session_path unless user_signed_in?
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end

  def host
  end

  def gallery
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
	def update
		# required for settings form to submit when password is left blank
		if params[:user][:password].blank?
			params[:user].delete("password")
			params[:user].delete("password_confirmation")
		end

		@user = User.find(current_user.id)
		if @user.update_attributes(params[:user])
			set_flash_message :notice, :updated
			sign_in @user, :bypass => true # Sign in bypassing validation in case his password changed
			redirect_to after_update_path_for(@user)
		else
			render :edit
		end
	end

	protected

		def after_sign_in_path_for(resource)
			admin_root_path
		end
end

app/controllers/speakers_controller.rb
class SpeakersController < ApplicationController
	before_filter :authenticate_user!
  def index
  	@speaker = Speaker.new
  	@speakers = Speaker.all
  end
end

app/controllers/thirteen_controller.rb
class ThirteenController < ApplicationController
  def index
  end

  def program
    @events = Event.where(show_in_program: true).where("start_time BETWEEN ? AND ?", DateTime.parse('29 Mar 2013'), DateTime.parse('1 Apr 2013')).order("start_time")
    @friday_events = Event.where("start_time BETWEEN ? AND ?", DateTime.parse('29 Mar 2013'), DateTime.parse('30 Mar 2013')).order("start_time")
    @saturday_events = Event.where("start_time BETWEEN ? AND ?", DateTime.parse('30 Mar 2013'), DateTime.parse('31 Mar 2013')).order("start_time")
    @sunday_events = Event.where("start_time BETWEEN ? AND ?", DateTime.parse('31 Mar 2013'), DateTime.parse('1 Apr 2013')).order("start_time")
  end

  def housing
  end

  def transportation
  end

  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
		@users = User.all
  end

  def show
		@user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/speakers_helper.rb
module SpeakersHelper
end

app/helpers/thirteen_helper.rb
module ThirteenHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_analytics.html.slim
javascript:
	var _gaq = _gaq || [];
	_gaq.push(['_setAccount', 'UA-7365777-4']);
	_gaq.push(['_setDomainName', 'dominicanstudentconference.com']);
	_gaq.push(['_trackPageview']);

	(function() {
	  var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
	  ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
	  var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
	})();

app/views/layouts/_carousel.html.slim
.container
	#myCarousel.carousel.slide
		.welcome-title
			| Wesleyan University
			span March 29 - 31, 2013
		.carousel-inner
			- if current_page? housing_path
				.active.item= image_tag "hotel.png"
			- else
				.active.item= image_tag "carousel1.png"
				.item= image_tag "carousel2.png"
				.item= image_tag "carousel3.png"
				.item= image_tag "carousel4.png"

app/views/layouts/_flash.html.slim
- if alert || notice
	.alert
		button.close data-dismiss="alert" type="button" ×
		= content_tag :div, alert || notice

app/views/layouts/_footer.html.slim
footer
	.social-media
		- mail_content = capture do
			i.icon-envelope
			| Email
		= mail_to "wesndsc@gmail.com", mail_content, target: "_blank", encode: "javascript"
		= link_to "https://www.facebook.com/pages/National-Dominican-Student-Conference/47619937613", target: "_blank" do
			i.icon-facebook-sign
			| Facebook
		= link_to "https://twitter.com/WesNDSC2013", target: "_blank" do
			i.icon-twitter
			| Twitter
		= link_to "http://ndsc2013.tumblr.com/", target: "_blank" do
			i.icon-tumblr
			| Tumblr

app/views/layouts/_navigation.html.slim
header.navbar.navbar-fixed-top
	nav.navbar-inner
		.container
			/! .btn-navbar is used as the toggle for collapsed navbar content
			a.btn.btn-navbar data-target=".nav-collapse" data-toggle="collapse"
				span.icon-bar
				span.icon-bar
				span.icon-bar

			= link_to "National Dominican Student Conference", root_path, class: "brand"

			.nav-collapse.collapse
				ul.nav
				ul.nav.pull-right
					/ li= link_to "Community", root_path
					li.visible-phone= link_to "Housing", housing_path
					li.visible-phone= link_to "Transportation", transportation_path
					li.visible-phone= link_to "Contact", contact_path
					li= link_to "About", about_path
					li= link_to "Gallery", gallery_path
					li= link_to "Host", host_path
					li.dropdown
						= link_to "#", class: "dropdown-toggle", "data-toggle" => "dropdown" do
							| History
							i.icon-caret-down
						ul.dropdown-menu
							li= link_to "Coming Soon!", root_path
							/ li= link_to "2012", root_path
							/ - if user_signed_in?
							/ 	li= link_to "Logout", destroy_user_session_path, method: :delete
							/ - else
							/ 	li= link_to "Login", new_user_session_path


					/ li= link_to "Edit Profile", edit_user_registration_path
					/ li.divider
					/ li= link_to "Logout", destroy_user_session_path, method: :delete
					/ - else
						/ li=
						/ li= link_to "Login", new_user_session_path
						/ li= link_to "Sign Up", new_user_registration_path

	= render "layouts/sub_navigation"

app/views/layouts/_sub_navigation.html.slim
.sub-navigation
	ul
		li= link_to "Home", root_path
		li= link_to "Program", program_path
		li.hidden-phone= link_to "Housing", housing_path
		li.hidden-phone= link_to "Transportation", transportation_path
		li.hidden-phone= link_to "Contact", contact_path
		li= link_to "REGISTER NOW", "http://wesndsc.eventbrite.com/", target: "_blank"

app/views/layouts/application.html.slim
doctype html
head
	meta charset="utf-8"
	meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"
	title National Dominican Student Conference
	meta name="description" content=(yield(:description) if content_for?(:description))
	meta name="viewport" content="width=device-width, initial-scale=1.0"
	= stylesheet_link_tag    "application", media: "all"
	= javascript_include_tag "//use.typekit.com/ier1ulg.js", "application"
	= csrf_meta_tags
	javascript:
		try{Typekit.load()}catch(e){}
		(function(d, s, id) {
			var js, fjs = d.getElementsByTagName(s)[0];
			if (d.getElementById(id)) return;
			js = d.createElement(s); js.id = id;
			js.src = "//connect.facebook.net/en_US/all.js#xfbml=1&appId=268332203237884";
			fjs.parentNode.insertBefore(js, fjs);
		}(document, 'script', 'facebook-jssdk'));
body class=(controller_name, action_name)
	#fb-root
	= render "layouts/navigation"
	#main role="main"
		.container
			.content
				.row
					.span9
						= render "layouts/flash"
						= render "layouts/carousel" if params[:controller] == "thirteen"
						= yield
				= render "layouts/footer"
				= render "layouts/analytics"
			/= debug(params) if Rails.env.development?

app/views/pages/about.html.slim
#about.page
	.section
		h1 About
		.section-body
			| NDSC is an annual conference that brings together Dominican college students and alumni from throughout the United States. Each year the NDSC Board undergoes a #{link_to "selection process", "#"} in which it accepts bids from potential host schools and selects where the next NDSC will be held.
	.section
		h4 Purpose
		ul style="margin-left: 20px"
			li Unite the numerous undergraduate and graduate Dominican student communities currently dispersed throughout the United States, with the goal of addressing and organizing them more effectively against the social and academic issues that continue to afflict them.
			br
			li Serve as an opportunity for the community to collectively celebrate the rich Dominican heritage that its members share and continue to keep alive in their respective college communities.
	.section
		h4 Objective
		blockquote
			| The conference's key objective is the building of
			strong  social and academic support networks
			|  among participants, particularly among those living in adjacent cities/regions. It believes that increasing collaboration between Dominican student groups and community organizations will help create a more comfortable, more familiar environment for Dominican students - and thus positively affecting the waning rates of retention and graduation from which the community suffers. We believe the sponsoring of this kind of networking will lead to each participant gaining a greater understanding of their own community, as well as foster a heightened desire to take socially significant action against the issues highlighted throughout the Conference.
	#history.section
		h1 History
		.section-body
			| The idea of a national conference was first proposed in 2007, at a Dominican Student Association - QuisqueYalies meeting by
			strong style="color: #006688"  Jamil Abreu
			|  '08. The group adopted the proposal, with the following individuals making up the conference planning committee:

			/ He observed one of the most significant issues in the community to be the lack of awareness of and communication between collegiate and community-based Dominican groups who, despite sharing similar interests and existing in the same general area, continued to operate independently of each other.

		= image_tag "founders.jpeg", :title => "QuisqueYalies 2007", :style => "max-width: 400px; float: right"
		ul
			li
				strong Jamil Abreu
				|  '08 (Co-Chair)
			li
				strong Lariely Garcia
				|  '09 (Co-Chair)
			li
				strong Damien Abreu
				|  '10
			li
				strong Ruben Harris
				|  '08
			li
				strong Jose Abreu
				|  '09
			li
				strong Brian Marmolejos
				|  '08
			li
				strong Mariel Novas
				|  '10
			li
				strong Nicolle Quintero
				|  '07
			li
				strong Joel Vargas
				|  '08
			li
				strong Prof. James Vreeland

	/ div style="clear:both"
	/ 		#board
	/ 			h1 Board

app/views/pages/gallery.html.slim
#gallery.page
	.section
		h1 Gallery
		/ .section-body
		iframe align="center" src="http://www.flickr.com/slideShow/index.gne?group_id=&user_id=9079568@N05&set_id=72157600403046951&text=" frameBorder="0" width="700" height="700" scrolling="no"

app/views/pages/host.html.slim
#host.page
	.section
		h1 Host
		.section-body
			|
				If your organization would like to host the NDSC, please send a proposal with the following information by 6PM on June 1st to #{mail_to "abreu.jamil@gmail.com", "this email", :encode => "javascript"}.
			BR
			|
				Please keep in mind that if selected, one of your group members (as chosen by the NDSC Board) will be required to form part of the selection committee for future conferences.

	.host-list
		ul
			li Organization Name, History, and Mission Statement
			li Conference Chair(s) Name and Email
			li E-board Names and Emails
			li Number of Active Members
			li Description of Previous Event(s) You Are Most Proud Of
			li Proposed Conference Dates (in April, and please make sure to avoid Easter weekend)
			li Description of Campus, Transportation, and Housing Options
			li Description of Potential Classrooms + Capacity and Availability of Largest Space
			li Preliminary Agenda for Entire Conference
			li Description of Potential Workshops and Speakers as Outlined in Your Agenda
			li Preliminary Budget (please include any restrictions your school may have on ticket sales and outside sponsorship)

	h4 In general, we will be looking for the teams that best show that they:
	.host-list.alert-success
		ul
			li Hold themselves to the highest standards of event quality, and excel in all aspects of professionalism (the best way to show this is via your proposal)
			li Are willing to focus on the conference for the entire year, and can promote the event properly
			li Can keep conference goers interested and engaged throughout the day.
			li Strike a balance between workshops and networking - emphasize the mingling of people from different schools, regions, etc.
			li Be creative, think BIG. Good Luck!

app/views/speakers/_speaker.html.slim
.speaker
	.speaker-image= image_tag speaker.image
	.speaker-content
		.speaker-name= speaker.name
		.speaker-description= speaker.description

app/views/speakers/index.html.slim
.page
	h1 Rolodex
	= simple_form_for @speaker, html: { class: "form-inline", multipart: true } do |f|
		= f.input :title, input_html: { class: "span1" }
		= f.input :first_name, input_html: { class: "span3" }
		= f.input :last_name, input_html: { class: "span3" }
		= f.input :suffix, input_html: { class: "span1" }
		= f.input :email
		= f.input :phone_number
		= f.input :organization
		= f.input :image
		= f.input :notes
		= f.input :description
	= render @speakers

app/views/thirteen/contact.html.slim
#contact.group
	.section
		h1 Contact
		.section-body
			| The NDSC planning committee is always committed to accessibility and transparency. Below is the contact information for Wesleyan team members. To contact the entire team please #{ mail_to "wesndsc@gmail.com", "click here", encode: "javascript" }.
		.contact-section
			ul
				span Co-Chairs:
				li
					| Dorisol Inoa, #{mail_to "dinoa@wesleyan.edu", "dinoa@wesleyan.edu", encode: "javascript"}
				li Judhanny Garcia, #{mail_to "jgarcia03@wesleyan.edu", "jgarcia03@wesleyan.edu", encode: "javascript"}
			ul
				span Content:
				li Keila Perez, #{mail_to "kperez@wesleyan.edu", "kperez@wesleyan.edu", encode: "javascript"}
			ul
				span Finance:
				li Kristie Cruz, #{mail_to "kcruz@wesleyan.edu", "kcruz@wesleyan.edu", encode: "javascript"}
				li Derek Jeffry, #{mail_to "djeffry@wesleyan.edu", "djeffry@wesleyan.edu", encode: "javascript"}
			ul
				span Publicity:
				li Stephanie Aracena, #{mail_to "saracena@wesleyan.edu", "saracena@wesleyan.edu", encode: "javascript"}
				li Konnie Dominguez, #{mail_to "kdominguez01@wesleyan.edu", "kdominguez01@wesleyan.edu", encode: "javascript"}
			ul
				span Hospitality:
				li Iliana Ortega, #{mail_to "iortega@wesleyan.edu", "iortega@wesleyan.edu", encode: "javascript"}
				li Victoria Ramos, #{mail_to "vramos@wesleyan.edu", "vramos@wesleyan.edu", encode: "javascript"}

app/views/thirteen/housing.html.slim
#housing.group
	.section
		h1 Housing
		.section-body
			/ | We will provide on-campus housing at no cost for students on a first come first serve basis, based on time of registration. If you indicate that you will require housing upon registering, you will receive an email confirming when your on-campus housing was secured. Please allow some time to receive this email, as it takes time to process the request. Students may be hosted in dorm rooms, apartments, or wood frame houses. We recommend all attendees staying on campus bring the following: business casual attire, casual attire, towel, necessary toiletries, sleeping bag and pillow for maximum comfort.
			/ BR
			/ | Students, recent graduates and professionals may also choose to be hosted at the official hotel for this conference, the Crowne Plaza, at a rate of only $84 per night plus taxes. To take advantage of this great offer please book your room using #{link_to "this link", "https://resweb.passkey.com/Resweb.do?mode=welcome_ei_new&eventID=10577225&utm_source=7945&utm_medium=email&utm_campaign=23213367"}.
			| We recommend all attendees bring the following: business casual attire, casual attire, and necessary toiletries. If you have been assigned on-campus housing, we also recommend bringing a towel, sleeping bag, and pillow for maximum comfort.
			BR
			| The official hotel for this conference is the Crowne Plaza, secured at a rate of only $84 per night plus taxes. To take advantage of this offer please book your room using #{link_to "this link", "https://resweb.passkey.com/Resweb.do?mode=welcome_ei_new&eventID=10577225&utm_source=7945&utm_medium=email&utm_campaign=23213367"}. The deadline for this rate is March 22nd. Alternative hotel options are listed below.
			BR
			| This rate applies whether you will have one to four people in a room. Select rooms can accommodate five people; please contact the hotel for more information.  If you will be staying in the hotel and will not have a vehicle to transport to and from Wesleyan, please let us know by sending us an email at #{mail_to "wesndsc@gmail.com", "wesndsc@gmail.com", encode: "javascript"}.

		br
		.hotel
			.hotel-name Marriott – Hartford Rocky Hill
			div Distance: 8.26 miles
			div Wesleyan Rate: Thu-Sat $89 / Sun-Wed $129
			div www.rockyhillmarriott.com
			div 100 Capital Boulevard, Rocky Hill, CT 06067
			div (860) 257-6000
		.hotel
			.hotel-name Comfort Inn & Suites
			div Distance: 7.57 miles
			div Wesleyan Rate: Start at $65.00
			div www.meridencomfortinn.com
			div 900 E. Main Street
			div Meriden, CT 06450
			div (203) 440-9600
		.hotel
			.hotel-name The Inn at Middletown
			div Contact: Beth Pruchnic
			div Distance: 0.45 miles
			div Wesleyan Rate: any night $129
			div $179.00 One Bedroom Suite
			div www.innatMiddletown.com
			div 70 Main Street
			div Middletown, CT 06457
			div (860) 854-6310

app/views/thirteen/index.html.slim
.section
	.section-body
		| Each year, NDSC provides the highest quality in educational and empowering workshops, prominent and inspirational speakers, culturally influential movie screenings, art exhibitions, networking events, and parties – all of which serve to educate, uplift, and unite the Dominican student community.

.section
	div class="fb-like-box hidden-phone" data-href="https://www.facebook.com/pages/National-Dominican-Student-Conference/47619937613" data-width="700" data-show-faces="true" data-stream="false" data-border-color="#FFFFFF" data-header="false"

	div class="fb-like-box visible-phone" data-href="https://www.facebook.com/pages/National-Dominican-Student-Conference/47619937613" data-width="280" data-show-faces="true" data-stream="false" data-border-color="#FFFFFF" data-header="false"

app/views/thirteen/program.html.slim
#program
	.section
		h1 Theme
		.section-body
			span In true Wesleyan fashion, the theme of this year’s conference is social justice, with the title
			b  “Peleando Injusticia, Haciendo Noticias,”
			span  which translates to
			i  Fighting Injustice and Making Headlines
			span . All of our workshops will focus on social justice issues that affect and transcend the Dominican community. We aim to have an action-based mindset when discussing the issues at hand by holding an organization fair to facilitate networking that will exposé Wesleyan students and conference participants to opportunities to make an impact. At the end of this conference, we hope that students will be empowered with tools to go back to their communities and start social movements that will make change.
	.section
		h1 style="border:0" Agenda*
		#agenda
			table.table.table-striped.table-bordered
				h4.agenda-date Friday, March 29, 2013
				tbody
					- @friday_events.each do |event|
						tr
							td.agenda-time-column= event.agenda_time
							td.agenda-name-column
								- if event.show_in_program
									= link_to event.name, "#event-#{event.id}"
								- else
									= event.name
							td.agenda-venue-column= event.venue

			table.table.table-striped.table-bordered
				h4.agenda-date Saturday, March 30, 2013
				tbody
					- @saturday_events.each do |event|
						tr
							td.agenda-time-column= event.agenda_time
							td.agenda-name-column
								- if event.show_in_program
									= link_to event.name, "#event-#{event.id}"
								- else
									= event.name
							td.agenda-venue-column= event.venue

			table.table.table-striped.table-bordered
				h4.agenda-date Sunday, March 31, 2013
				tbody
					- @sunday_events.each do |event|
						tr
							td.agenda-time-column= event.agenda_time
							td.agenda-name-column
								- if event.show_in_program
									= link_to event.name, "#event-#{event.id}"
								- else
									= event.name
							td.agenda-venue-column= event.venue
			span style="font-size: 12px" * subject to change

	- @events.each do |event|
		.event-section.sub-section
			span id="event-#{event.id}"
			h1= event.name
			- if event.description
				.section-body
					.event-description
						= event.description.html_safe
			.event-speakers
				- event.speakers.sort_by!{|speaker| speaker.priority}.each do |speaker|
					.event-speaker.group
						.event-speaker-image= image_tag speaker.image, class: "img-polaroid"
						.event-speaker-content
							.event-speaker-name= speaker.name
							.event-speaker-description= speaker.description

app/views/thirteen/transportation.html.slim
#housing.group
	.section
		h1 Transportation
		.section-body
			| Wesleyan University is located at 45 Wyllys Ave., Middletown, CT. - less than two hours away from NYC, Boston and Providence. It is easily accessible by car, bus, Metro-North or Amtrak. The Megabus, Metro-North and Amtrak each stop at New Haven station, only 30 minutes from Wesleyan.
	.sub-section
		table.table.table-striped.table-bordered
			h1 NDSC SHUTTLE
			.sub-section-body
				| Transportation to and from the New Haven station will be provided by WesQuisqueya through school buses. The cost will be $15 per person each way, #{link_to "click here to purchase your ticket in advance", "http://purchase.tickets.com/buy/TicketPurchase?orgid=36087", target: "_blank"}. *This is the only shuttle time we are organizing. We encourage you to buy your NDSC shuttle ticket asap, as a taxi from New Haven to Wesleyan costs $70 each way. Please email us with any concerns at wesndsc@gmail.com
			thead
				tr
					th Day
					th Leaves
					th Time
			tbody
				tr
					td Friday
					td New Haven
					td 6:30PM
				tr
					td Saturday
					td Wesleyan
					td 12PM

	/ .sub-section
	/ 	table.table.table-striped.table-bordered
	/ 		h1 WESLEYAN SHUTTLE
	/ 		.sub-section-body
	/ 			| Transportation to and from the New Haven station can be provided by Wesleyan shuttles. Wesleyan provides shuttles to New Haven every Friday, Saturday and Sunday. Shuttle reservations cost $10 per person and need to be made in advance. #{link_to "Click Here for more information", "http://www.wesleyan.edu/transportation/newhaven_shuttle.html", target: "_blank"}
	/ 		thead
	/ 			tr
	/ 				th Day
	/ 				th Wesleyan to New Haven
	/ 				th New Haven to Wesleyan
	/ 		tbody
	/ 			tr
	/ 				td Friday
	/ 				td 6pm
	/ 				td 7pm
	/ 			tr
	/ 				td Saturday
	/ 				td 10am
	/ 				td 11pm
	/ 			tr
	/ 				td Sunday
	/ 				td 12pm
	/ 				td 1pm

	.section.sub-section
		h1 BY TRAIN
		.sub-section-body
			| Take Metro North to New Haven. #{link_to "Click here", "http://as0.mta.info/mnr/schedules/sched_form.cfm", target: "_blank"} to look at the schedules. From New Haven, Wesleyan is only a 35 minute cab ride away. You can also choose to take the Wesleyan shuttle - the schedule is listed above. Take Amtrak to New Haven, and then take shuttle to Wesleyan. You can also take the Amtrak to the Meriden station, which is only a 15 minute drive away. From there you can take a $25 cab to Wesleyan.
	.section.sub-section
		h1 BY BUS
		.sub-section-body
			| Take MegaBus to New haven. #{link_to "Click here", "http://megabus.com/", target: "_blank"} to buy your bus ticket.
	.section.sub-section
		h1 BY CAR
		.sub-section-body
			ul
				li From Hartford and points north take I-91 south to Exit 22 for Route 9 southbound. At exit 15, turn right onto Route 66 West (Washington Street), turn left onto High Street.
				li From New Haven, New York and points south Take I-95 North to I-91 North. At exit 18, take Route 691/66 East. Route 66 becomes Washington Street in Middletown. Take right onto High Street. Or, take I-95 north to the Merritt/Wilbur Cross Parkway (Route 15 North) to Route 66 Eastbound. Take right onto High Street.
				li From Waterbury and points west take I-84 East. Take exit 27 to Route 691/66 East. Route 66 becomes Washington Street in Middletown. Take right onto High Street. (Please refer to the notice above for changed traffic conditions on Route 66/Washington Street.)
				li From Boston and points northeast take the Massachusetts Turnpike (I-90) West to Exit 9 for I-84 West to Hartford. Take exit 57 over the Charter Oak Bridge and follow the signs to I-91 South. Take I-91 south to exit 22 for Route 9 Southbound, At exit 15, turn right onto Route 66 West (Washington Street), turn left onto High Street.
				li Or, take I-95 South through Providence, then take Exit 69 to Route 9 North (approximately 26 miles to Middletown). At exit 15, turn left.

app/views/users/_user.html.slim
.user.group
  .user-name= user.name
  .user-description= user.description

app/views/users/index.html.slim
.section
	.section-body
		| Each year, NDSC provides the highest quality in educational and empowering workshops, prominent and inspirational speakers, culturally influential movie screenings, art exhibitions, networking events, and parties – all of which serve to educate, uplift, and unite the Dominican student community.

.section
	h1 Pon'te al dia
	.section-body
		div style="background: #FFF" class="fb-like-box" data-href="https://www.facebook.com/pages/National-Dominican-Student-Conference/47619937613" data-width="660" data-show-faces="true" data-stream="false" data-border-color="#DDDDDD" data-header="false"

app/views/users/show.html.slim
h1 Users#show
p Find me in app/views/users/show.html.slim